controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
  - name: fake_gripper_controller
    joints:
      - finger_joint1
